### ISSUE TITLE
No scrollbar after transform

### ISSUE THREAD

**Issue by erwanpoupard** [mercs600/vue2-perfect-scrollbar#3]
My perfect-scrollbar is not visible : 

```css
.sidebar {
  transform: translateX(-100%);
}
```
```html 
<perfect-scrollbar class="sidebar">
     My sidebar
</perfect-scrollbar>
```

after a click, translateX property is set to 0% and the sidebar is visible. But the scrollbars doesnt appear
